### ISSUE TITLE
Syntax error at loader.go:313

### ISSUE THREAD

**Issue by vilyzzz** [jayjanssen/myq-tools#20]
:~/code/myq-tools$ git clone https://github.com/jayjanssen/myq-tools.git
Cloning into 'myq-tools'...
remote: Counting objects: 855, done.
remote: Total 855 (delta 0), reused 0 (delta 0), pack-reused 855
Receiving objects: 100% (855/855), 7.84 MiB | 6.36 MiB/s, done.
Resolving deltas: 100% (566/566), done.
Checking connectivity... done.
:~/code/myq-tools$ go run myq_status.go 
myq_status.go:7:2: cannot find package "github.com/jayjanssen/myq-tools/myqlib" in any of:
    /usr/lib/go/src/pkg/github.com/jayjanssen/myq-tools/myqlib (from $GOROOT)
    ($GOPATH not set)
:~/code/myq-tools$ sed -i 's:github.com/jayjanssen/myq-tools/myqlib:../myq-tools/myqlib:g' myq_status.go 
:~/code/myq-tools$ GOPATH=/home/user/code/ go run myq_status.go 
# _/home/user/code/myq-tools/myqlib

myqlib/loader.go:313: syntax error: unexpected range, expecting {
myqlib/loader.go:323: non-declaration statement outside function body
myqlib/loader.go:326: non-declaration statement outside function body
myqlib/loader.go:327: syntax error: unexpected }

**Comment by jayjanssen** [comment]
What version of Go are you using?

**Comment by vilyzzz** [comment]
It on Ubuntu trusty 14.04:

# dpkg -l | grep  golang
ii  golang                                    2:1.2.1-2ubuntu1                        all          Go programming language compiler - metapackage
ii  golang-doc                                2:1.2.1-2ubuntu1                        all          Go programming language compiler - documentation
ii  golang-go                                 2:1.2.1-2ubuntu1                        amd64        Go programming language compiler
ii  golang-go-linux-amd64                     2:1.2.1-2ubuntu1                        amd64        Go standard library compiled for linux_amd64
ii  golang-src                                2:1.2.1-2ubuntu1                        amd64        Go programming language compiler - source files

**Comment by jayjanssen** [comment]
Looks like Go 1.2 I guess?

I'm not seeing the same issue on go 1.5, which is long since stable, I'd
consider upgrading.  I developed this on Go 1.4, I can't speak for
compatibility with earlier versions.

On Fri, Feb 5, 2016 at 7:54 AM, vilyzzz <notifications@github.com> wrote:

> It on Ubuntu trusty 14.04:
> dpkg -l | grep golang
>
> ii golang 2:1.2.1-2ubuntu1 all Go programming language compiler -
> metapackage
> ii golang-doc 2:1.2.1-2ubuntu1 all Go programming language compiler -
> documentation
> ii golang-go 2:1.2.1-2ubuntu1 amd64 Go programming language compiler
> ii golang-go-linux-amd64 2:1.2.1-2ubuntu1 amd64 Go standard library
> compiled for linux_amd64
> ii golang-src 2:1.2.1-2ubuntu1 amd64 Go programming language compiler -
> source files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jayjanssen/myq-tools/issues/20#issuecomment-180343950>
> .
>



-- 
Jay Janssen
Managing Consultant, Percona
https://about.me/jay.janssen

**Comment by vilyzzz** [comment]
Thanks for response. Well - it does not work with Go 1.3.3 (from ubuntu trusty-backports) either. I'll probably give it a shot later if I can get Go >=1.4 
I'm restricted to repo software only.

**Comment by jayjanssen** [comment]
I wouldn't expect that much syntactical differences in Go, something else
must be incorrect.

I noticed your fight with the library.  How I do that is that my GOPATH is:

~/Src/golang

and I have the full git repo checked out INSIDE of that path like this


~/Src/golang/src/github.com/jayjanssen/myq-tools/

and a symlink:

ln -s ~/Src/golang/src/github.com/jayjanssen/myq-tools/ ~/Src/myq-tools


~/Src/myq-tools]$ go run myq_status.go
myq-tools  ()

Usage:
  myq_status [flags] <view>

Description:
  iostat-like views for MySQL servers



  Not sure if that is the difference or not, but may be worth a check.



On Fri, Feb 5, 2016 at 8:09 AM, vilyzzz <notifications@github.com> wrote:

> Thanks for response. Well - it does not work with Go 1.3.3 (from ubuntu
> trusty-backports) either. I'll probably give it a shot later if I can get
> Go >=1.4
> I'm restricted to repo software only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jayjanssen/myq-tools/issues/20#issuecomment-180350395>
> .
>



-- 
Jay Janssen
Managing Consultant, Percona
https://about.me/jay.janssen

**Comment by jayjanssen** [comment]
I will also point out that there are simply pre-built linux binaries in the
Releases tab here on github.

On Fri, Feb 5, 2016 at 8:20 AM, Jay Janssen <jay.janssen@percona.com> wrote:

> I wouldn't expect that much syntactical differences in Go, something else
> must be incorrect.
>
> I noticed your fight with the library.  How I do that is that my GOPATH is:
>
> ~/Src/golang
>
> and I have the full git repo checked out INSIDE of that path like this
>
>
> ~/Src/golang/src/github.com/jayjanssen/myq-tools/
>
> and a symlink:
>
> ln -s ~/Src/golang/src/github.com/jayjanssen/myq-tools/ ~/Src/myq-tools
>
>
> ~/Src/myq-tools]$ go run myq_status.go
> myq-tools  ()
>
> Usage:
>   myq_status [flags] <view>
>
> Description:
>   iostat-like views for MySQL servers
>
>
>
>   Not sure if that is the difference or not, but may be worth a check.
>
>
>
> On Fri, Feb 5, 2016 at 8:09 AM, vilyzzz <notifications@github.com> wrote:
>
>> Thanks for response. Well - it does not work with Go 1.3.3 (from ubuntu
>> trusty-backports) either. I'll probably give it a shot later if I can get
>> Go >=1.4
>> I'm restricted to repo software only.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jayjanssen/myq-tools/issues/20#issuecomment-180350395>
>> .
>>
>
>
>
> --
> Jay Janssen
> Managing Consultant, Percona
> https://about.me/jay.janssen
>



-- 
Jay Janssen
Managing Consultant, Percona
https://about.me/jay.janssen

**Comment by vilyzzz** [comment]
Thank you for pointing it out. I completely missed pre-build binaries. It works fine.
