### ISSUE TITLE
cannot find package "github.com/jayjanssen/myq-tools/myqlib"

### ISSUE THREAD

**Issue by GriffReborn** [jayjanssen/myq-tools#21]
I've YUM installed GO on Centos 7.2 and tried to deploy myq-tools both by downloading and extracting from ZIP, and by GIT clone.  Same results :

myq_status.go:7:2: cannot find package "github.com/jayjanssen/myq-tools/myqlib" in any of:
        /usr/lib/golang/src/github.com/jayjanssen/myq-tools/myqlib (from $GOROOT)
        /home/golang/src/github.com/jayjanssen/myq-tools/myqlib (from $GOPATH)

The only way I've been able to get this to work is to create the whole expected path by adding in /src/github.com/jayjannsen and moving myq-tools into that location.  I then have to CD into that new location to run the tool.  

Platform is Centos 7.2.  

Steps taken

sudo yum install git
cd /home/golang/
git clone https://github.com/jayjanssen/myq-tools.git
go run myq_status.go
cd myq-tools/
go run myq_status.go

Returns error as above.

Here is my GO env from the server I used 

GOARCH="amd64"
GOBIN="/usr/lib/golang/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/golang"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

To work around the issue :

mkdir /home/golang/src
mkdir /home/golang/src/github.com
mkdir /home/golang/src/github.com/jayjanssen
mv /home/golang/myq-tools /home/golang/src/github.com/jayjanssen/

Then to run:
cd /home/golang/src/github.com/jayjanssen/myq-tools/
go run myq_status.go
go run myq_status.go wsrep

This all feels a little clunky.  Is this expected behavior? Did I do something wrong?

**Comment by jayjanssen** [comment]
I won't claim to be the most proficient Go programmer, neither have I been doing much here, so I'm sure there may be better ways of doing this.

That being said, this is only necessary if you intend to do some extra development.  If not, I have prebuilt binaries available here:  https://github.com/jayjanssen/myq-tools/releases
