### ISSUE TITLE
what is ist and %ref mean

### ISSUE THREAD

**Issue by Fanduzi** [jayjanssen/myq-tools#23]
thanks

**Comment by jayjanssen** [comment]
IST is the amount of transactions in the local gcache (the more here, the longer another node can go offline for).
https://github.com/jayjanssen/myq-tools/blob/master/myqlib/view_defaults.go#L285

There is no %ref, but %ef is the % of wsrep_slave_threads being used.
https://github.com/jayjanssen/myq-tools/blob/master/myqlib/view_defaults.go#L289

**Comment by Fanduzi** [comment]
thank you very much!
