### ISSUE TITLE
Re-add view for galera statistics

### ISSUE THREAD

**Issue by b2cc** [jayjanssen/myq-tools#24]
Hello!

Do you see the possibility to re-add the view for the galera statistics to the latest version? We've been using it for monitoring and it was really handy to quickly get the cluster status.

----

Version 1.x
```
~# ./myq_status -a -uroot -a "-S /run/mysql.sock" wsrep

galera / node01 (idx: 1) / Galera 25.3.35(r545d0bf)
         Cluster  Node       Outbound      Inbound       FlowC     Conflct Gcache     Appl
    time P cnf  # stat laten msgs data que msgs data que pause snt lcf bfa   ist  idx  %ef
08:58:36 P  61  3 Sync 0.0ns    6 4.3K   0 1.1m 834M   0   0ns   0   0   0  323k    9 100%
```

----

Version: 971e478 from `main` branch
```
./myq_status -u root -S /run/mysql.sock wsrep
  view wsrep not found
  myq-tools  ()
```

----

Thanks in advance,
David

**Comment by jayjanssen** [comment]
Hi there, glad you find the tool useful.  I'd suggest you continue using the v1 branch for now.   I had been doing more work on v2, but that has stalled a bit.   I am also not using Galera these days, so I don't have a lot of incentive to work on this view.

The view in question can be seen here in v1: https://github.com/jayjanssen/myq-tools/blob/v1/myqlib/view_defaults.go#L198-L291

The new version uses a [yaml file to define the views](https://github.com/jayjanssen/myq-tools/blob/main/viewer/view_defaults.yaml) but I have not yet figured out how to handle the 'FuncCol' construct I used in v1.  I believe most/all of the other cols in v1 would be easy to add to v2.

**Comment by jayjanssen** [comment]
hello @b2cc  -- I got inspired to do a bit of dev.  Can you take a look at the PR I linked here and corresponding branch to see what you think?  I couldn't match it exactly to the old version, but this is pretty close.

**Comment by b2cc** [comment]
Resolved in https://github.com/jayjanssen/myq-tools/pull/25 👍
